"""empty message

Revision ID: 158e46be773d
Revises: 
Create Date: 2019-11-19 17:43:05.739192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '158e46be773d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=90), nullable=False),
    sa.Column('token', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conference_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('organizer', sa.String(length=150), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=80), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('organizer_email', sa.String(length=100), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('impact_conference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('h_index', sa.Integer(), nullable=True),
    sa.Column('organizer', sa.String(length=150), nullable=True),
    sa.Column('location', sa.String(length=80), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('university_program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university', sa.String(length=50), nullable=False),
    sa.Column('program', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=90), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('pending_emails',
    sa.Column('email', sa.String(length=300), nullable=False),
    sa.Column('confname', sa.String(length=150), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=80), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('email', 'confname'),
    sa.UniqueConstraint('confname')
    )
    op.create_table('user_program',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['university_program.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_program')
    op.drop_table('pending_emails')
    op.drop_table('user')
    op.drop_table('university_program')
    op.drop_table('impact_conference')
    op.drop_table('conference_item')
    op.drop_table('auth_token')
    # ### end Alembic commands ###
